trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(ARM_TENANT_ID)

steps:
/*- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
*/
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.0'

- script: |
    terraform init
  displayName: 'Terraform Init'

- script: |
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    terraform plan -var-file="terraform.tfvars"
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve -var-file="terraform.tfvars"
  displayName: 'Terraform Apply'
